### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by yamnayemara** [contentful/contentful-import#245]
while trying to run `contentful space X` i got 
`/usr/local/Cellar/contentful-cli/1.4.17/libexec/lib/node_modules/contentful-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/contentful-cli/1.4.17/libexec/lib/node_modules/contentful-cli/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)`

node version v8.11.2
contentful version 1.4.17
mac

**Comment by amandasage** [comment]
Hi there,

Have you tried updating to the latest version of Node (v12 or higher)? https://nodejs.org/en/about/releases/

**Comment by yamnayemara** [comment]
yes, It solved the problem, I forgat to update the ticket with that. thanks
