### ISSUE TITLE
Problem importing content generated by the export tool

### ISSUE THREAD

**Issue by davetao** [contentful/contentful-import#3]
I was attempting to import the contents of the contentful-export tool into a new space when i came across the following crash.

TypeError: Cannot read property 'url' of null 

ERR! Failed within
 TypeError: Cannot read property 'url' of null
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/transform/transformers.js:36:44
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/lodash/_baseReduce.js:18:9
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/lodash/_createBaseFor.js:17:11
ERR! Failed within
     at baseForOwn (/usr/local/lib/node_modules/contentful-import/node_modules/lodash/_baseForOwn.js:13:20)
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/lodash/_createBaseEach.js:17:14
ERR! Failed within
     at baseReduce (/usr/local/lib/node_modules/contentful-import/node_modules/lodash/_baseReduce.js:15:3)
ERR! Failed within
     at reduce (/usr/local/lib/node_modules/contentful-import/node_modules/lodash/reduce.js:48:10)
ERR! Failed within
     at Object.assets (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/transform/transformers.js:34:57)
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/transform/transform-space.js:14:40
ERR! Failed within
     at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)
ERR! Failed within
     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)
ERR! Failed within
     at MappingPromiseArray.PromiseArray._iterate (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise_array.js:113:31)
ERR! Failed within
     at MappingPromiseArray.init (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise_array.js:77:10)
ERR! Failed within
     at MappingPromiseArray._asyncInit (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:30:10)
ERR! Failed within
     at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:12)
ERR! Failed within
     at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:148:10)
ERR! Failed within
     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)
ERR! Failed within
  TypeError: Cannot read property 'url' of null
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/transform/transformers.js:36:44
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/lodash/_baseReduce.js:18:9
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/lodash/_createBaseFor.js:17:11
ERR! Failed within
     at baseForOwn (/usr/local/lib/node_modules/contentful-import/node_modules/lodash/_baseForOwn.js:13:20)
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/lodash/_createBaseEach.js:17:14
ERR! Failed within
     at baseReduce (/usr/local/lib/node_modules/contentful-import/node_modules/lodash/_baseReduce.js:15:3)
ERR! Failed within
     at reduce (/usr/local/lib/node_modules/contentful-import/node_modules/lodash/reduce.js:48:10)
ERR! Failed within
     at Object.assets (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/transform/transformers.js:34:57)
ERR! Failed within
     at /usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/transform/transform-space.js:14:40
ERR! Failed within
     at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)
ERR! Failed within
     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)
ERR! Failed within
     at MappingPromiseArray.PromiseArray._iterate (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise_array.js:113:31)
ERR! Failed within
     at MappingPromiseArray.init (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise_array.js:77:10)
ERR! Failed within
     at MappingPromiseArray._asyncInit (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:30:10)
ERR! Failed within
     at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:12)
ERR! Failed within
     at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:148:10)
ERR! Failed within
     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)

**Comment by Khaledgarbaya** [comment]
hi @davetao ,
Can you specify the versiion of the contentful-export and contentful-import you used ?

**Comment by Khaledgarbaya** [comment]
hi @davetao ,
I pushed a new major version for contentful-export and contentful-import, can you try with those new ones and tell me if you still have the same problem.

**Comment by gearboxdesign** [comment]
Hi @Khaledgarbaya, I am also having an issue importing content from an export, it is not the same issue described above.

I get a 404 response when trying to import the resources:

ERR! NotFound: {
  "request": {
    "url": "https://api.contentful.com:443/spaces/qa9eo8psvy4v/locales/1zSpSBgeOniliHN6bkLwiB",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/vnd.contentful.management.v1+json",
      "X-Contentful-User-Agent": "contentful-management.js/1.2.1",
      "Authorization": "Bearer efbfb428474d41b7e8f2863e84ec25721e08684dff2d1f0f606d31383a13d50d",
      "user-agent": "node.js/v6.1.0",
      "Accept-Encoding": "gzip"
    },
    "method": "delete"
  },
  "status": 404,
  "statusText": "Not Found",
  "requestId": "674e26841bd941153374adea1f6badbf",
  "message": "The resource could not be found."
} 

I may have missed something, the export seemed to go through just fine, and I am using the same tokens to import.

I am sure that all of the content has been published in the exportee and that the user account I am using has owner access.

I am attempting to import content from another organization's space, not sure if this helps...

Thanks so much.

**Comment by Khaledgarbaya** [comment]
Hi @gearboxdesign , You will need a new token from the new space's organisation management token to be able to import your content

**Comment by gearboxdesign** [comment]
I'll give that a try :)

**Comment by axe312ger** [comment]
Closing issue since no feedback was received for several months. If this still occurs, feel free to open a new issue :)

**Comment by TorbenDalgaard** [comment]
Having the same issue.

contentful-import@5.0.2-beta4
contentful-batch-libs@8.0.0-beta4

 Any suggestion ?

"ts": "2017-12-15T12:13:36.234Z",
    "level": "error",
    "error": {
      "stacktrace": [
        "TypeError: Cannot read property 'sys' of undefined",
        "/Users/my_user/.npm-global/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/push-to-space.js:344:46",
        "Array.filter (native)",
        "publishEntities (/Users/my_user/.npm-global/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/push-to-space.js:343:36)",
        "Task.task (/Users/my_user/.npm-global/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/push-to-space.js:230:14)",
        "Promise.resolve.then.then.skipped (/Users/my_user/.npm-global/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/node_modules/listr/lib/task.js:169:30)",
        "<anonymous>"
      ]
    }

**Comment by axe312ger** [comment]
Looks like your entity is malformed. We are aware of these cases and looking for solutions, one might be:
https://github.com/contentful/contentful-batch-libs/pull/137

**Comment by axe312ger** [comment]
If it is urgent, feel free to create a support ticket at https://www.contentful.com/support/. We can help you there more efficent since we can exchange private information like your imported dataset to analyse it here in the office.

Have great weekend,
Benedikt

**Comment by Kian-Aghaei** [comment]
Hi, I encountered a similar problem,

I export from an environment without any problem:
`contentful space export --space-id=[ID] --environment-id=redesign --export-dir='config/migrations/exports' --skip-webhooks=true --skip-content=true --skip-roles=true`

and tried to import it into another environment in the same organization and same space:
`contentful space import --space-id=[ID] --environment-id=[destination environment] --content-file config/migrations/exports/[fileName].json --skip-webhooks=true --skip-content=true --skip-roles=true`

then I received 404:

```
[
  {
    "ts": "2020-06-29T10:42:12.103Z",
    "level": "error",
    "error": {
      "originalError": {
        "name": "NotFound",
        "message": "{\n  \"status\": 404,\n  \"statusText\": \"Not Found\",\n  \"message\": \"The resource could not be found.\",\n  \"details\": {},\n  \"request\": {\n    \"url\": \"environments/[excopy]\",\n    \"headers\": {\n      \"Accept\": \"application/json, text/plain, */*\",\n      \"Content-Type\": \"application/vnd.contentful.management.v1+json\",\n      \"X-Contentful-User-Agent\": \"app contentful.cli/1.3.38; feature space-import; sdk contentful-management.js/5.26.3; platform node.js/v12.16.3; os Linux/5.6.19-300.fc32.x86_64;\",\n      \"Authorization\": \"Bearer ...0fMNs\",\n      \"user-agent\": \"node.js/v12.16.3\",\n      \"Accept-Encoding\": \"gzip\"\n    },\n    \"method\": \"get\"\n  },\n  \"requestId\": \"8c75e7c8786ed13b3dead6d1992bd5e1\"\n}"
      },
      "data": {
        "status": 404,
        "statusText": "Not Found",
        "message": "The resource could not be found.",
        "details": {
        },
        "request": {
          "url": "environments/[excopy]",
          "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/vnd.contentful.management.v1+json",
            "X-Contentful-User-Agent": "app contentful.cli/1.3.38; feature space-import; sdk contentful-management.js/5.26.3; platform node.js/v12.16.3; os Linux/5.6.19-300.fc32.x86_64;",
            "Authorization": "Bearer ...0fMNs",
            "user-agent": "node.js/v12.16.3",
            "Accept-Encoding": "gzip"
          },
          "method": "get"
        },
        "requestId": "8c75e7c8786ed13b3dead6d1992bd5e1"
      }
    }
  }
]
```

How can I solve this? It is not clear to me what went wrong.
Thank you in advance.

**Comment by phoebeschmidt** [comment]
Hi @Kian-Aghaei ,

Was the environment you are importing to empty or did it already have some content in it?
Also, `[excopy]` is an invalid environment ID. (Or did you remove your env id for GH issue? :) )

**Comment by axe312ger** [comment]
@Kian-Aghaei I think I had 404s as well when the access token had no access to the environment
