### ISSUE TITLE
import issue "cannot read property 'sys' of null

### ISSUE THREAD

**Issue by temelj** [contentful/contentful-import#35]
I am using the latest contentful-export v4.5.2 to generate an export of a space-id: 3d7n2zsyfd75

I am using the latest contentful-import v4.3.0 to import the data into a newly created space-id: ga4t540okd9e
```
info import Contentful Import Tool
info import Importing data ...
info Checking if destination space already has any content and retrieving it
info Pushing content to destination space
info Updated Locale Australian English
info Created ContentType IntroSlides
info Created ContentType NavPage
info Created ContentType VideoItem
info Created ContentType ArticleItem
info Created ContentType GeneralPage
info Created ContentType VideoPage
info Created ContentType NewsItem
info Created ContentType BasicPage
info Created ContentType VideoCategory
info Created ContentType ThoughtArticlePage
info Created ContentType NewsPage
info Published ContentType NavPage
info Published ContentType NewsItem
info Published ContentType IntroSlides
info Published ContentType GeneralPage
info Published ContentType VideoItem
info Published ContentType ArticleItem
info Published ContentType NewsPage
info Published ContentType ThoughtArticlePage
info Published ContentType BasicPage
info Published ContentType VideoCategory
info Published ContentType VideoPage
ERR! import TypeError: Cannot read property 'sys' of null
ERR! import     at _loop (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:45:32)
ERR! import     at C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:63:26
ERR! import     at Array.map (native)
ERR! import     at C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:43:60
ERR! import     at tryCatcher (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Promise._settlePromiseFromHandler (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:512:31)
ERR! import     at Promise._settlePromise (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:569:18)
ERR! import     at Promise._settlePromise0 (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:614:10)
ERR! import     at Promise._settlePromises (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:693:18)
ERR! import     at Promise._fulfill (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:638:18)
ERR! import     at MappingPromiseArray.PromiseArray._resolve (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise_array.js:126:19)
ERR! import     at MappingPromiseArray._promiseFulfilled (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\map.js:101:18)
ERR! import     at Promise._settlePromise (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:574:26)
ERR! import     at Promise._settlePromise0 (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:614:10)
ERR! import     at Promise._settlePromises (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:693:18)
ERR! import     at Async._drainQueue (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:133:16)
ERR! import  TypeError: Cannot read property 'sys' of null
ERR! import     at _loop (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:45:32)
ERR! import     at C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:63:26
ERR! import     at Array.map (native)
ERR! import     at C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:43:60
ERR! import     at tryCatcher (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Promise._settlePromiseFromHandler (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:512:31)
ERR! import     at Promise._settlePromise (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:569:18)
ERR! import     at Promise._settlePromise0 (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:614:10)
ERR! import     at Promise._settlePromises (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:693:18)
ERR! import     at Promise._fulfill (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:638:18)
ERR! import     at MappingPromiseArray.PromiseArray._resolve (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise_array.js:126:19)
ERR! import     at MappingPromiseArray._promiseFulfilled (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\map.js:101:18)
ERR! import     at Promise._settlePromise (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:574:26)
ERR! import     at Promise._settlePromise0 (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:614:10)
ERR! import     at Promise._settlePromises (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:693:18)
ERR! import     at Async._drainQueue (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:133:16)
ERR! import TypeError: Cannot read property 'sys' of null
ERR! import     at _loop (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:45:32)
ERR! import     at C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:63:26
ERR! import     at Array.map (native)
ERR! import     at C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:43:60
ERR! import     at tryCatcher (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Promise._settlePromiseFromHandler (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:512:31)
ERR! import     at Promise._settlePromise (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:569:18)
ERR! import     at Promise._settlePromise0 (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:614:10)
ERR! import     at Promise._settlePromises (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:693:18)
ERR! import     at Promise._fulfill (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:638:18)
ERR! import     at MappingPromiseArray.PromiseArray._resolve (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise_array.js:126:19)
ERR! import     at MappingPromiseArray._promiseFulfilled (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\map.js:101:18)
ERR! import     at Promise._settlePromise (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:574:26)
ERR! import     at Promise._settlePromise0 (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:614:10)
ERR! import     at Promise._settlePromises (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:693:18)
ERR! import     at Async._drainQueue (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:133:16)
ERR! import  Failed within
ERR! import  TypeError: Cannot read property 'sys' of null
ERR! import     at _loop (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:45:32)
ERR! import     at C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:63:26
ERR! import     at Array.map (native)
ERR! import     at C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\contentful-batch-libs\dist\push\push-to-space.js:43:60
ERR! import     at tryCatcher (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\util.js:16:23)
ERR! import     at Promise._settlePromiseFromHandler (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:512:31)
ERR! import     at Promise._settlePromise (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:569:18)
ERR! import     at Promise._settlePromise0 (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:614:10)
ERR! import     at Promise._settlePromises (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:693:18)
ERR! import     at Promise._fulfill (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:638:18)
ERR! import     at MappingPromiseArray.PromiseArray._resolve (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise_array.js:126:19)
ERR! import     at MappingPromiseArray._promiseFulfilled (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\map.js:101:18)
ERR! import     at Promise._settlePromise (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:574:26)
ERR! import     at Promise._settlePromise0 (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:614:10)
ERR! import     at Promise._settlePromises (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\promise.js:693:18)
ERR! import     at Async._drainQueue (C:\Users\Temelj\AppData\Roaming\npm\node_modules\contentful-import\node_modules\bluebird\js\release\async.js:133:16)
```

**Comment by temelj** [comment]
An Export/Import works using the following versions:

contentful-export v4.3.0
contentful-import v4.2.0

**Comment by axe312ger** [comment]
Hey @temelj,
sorry for the inconvenience, your bug is related to a rare edge case which we forgot to cover in the last refactoring.

The next version of the batch-libs should be published in a few minutes, please upgrade your dependencies, the bug should be gone then.

If it still appears, feel free to reopen the issue :)

All the best,
Benedikt

**Comment by temelj** [comment]
Hi,

Thank you for that update. I will re-test with the updated libs.

I have another question as I've reverted to the older versions, the asset
media count in the original space is LESS than in the destination space.

Im assuming that in the contentful website,  the ALL media count does not
include Archived items. The count does add up in that case.

However, the contentful-import tool treated published, draft and archived
assets the same way and when copied to the new destination space, they are
all Draft (including the archived ones). Is this expected /know behaviour
or am I doing something wrong with the import?

Thank you again.

**Comment by axe312ger** [comment]
@temelj I just tried it out and my draft assets stayed draft while the tool published the ones, that were published before.

Please try with the newest version and come back here if the error still occurs. If you think it is related to your space/data, feel free to file an issue including your space id's here: https://support.contentful.com/hc/en-us/requests/new

Benedikt

**Comment by temelj** [comment]
I can confirm that I'm using the latest version (which includes the contentful-batch-libs v5.6.2)

The contentful-import took 35 minutes.
Content Types         11
Editor Interfaces        9
Entries                   230
Assets                  1359       
Locales                      1    
Webhooks                 0   
Roles                        3

Assets are fine with a count of 1359.
Entries is reported to be  230, however I only see 144 entries in the contentful.com for the space.

**Comment by temelj** [comment]
Close this one 

the original issue is resolved with updating to use contentful-batch-libs v5.6.2
