### ISSUE TITLE
ERR! TypeError: expecting an array or an iterable object but got [object Null] 

### ISSUE THREAD

**Issue by spencerkohan** [contentful/contentful-import#6]
I'm attempting to re-import the content exported by contentful-export and I get this error bubbling up from bluebird.  Any idea what this is?

```
ERR! TypeError: expecting an array or an iterable object but got [object Null] 
ERR! Failed within
 TypeError: expecting an array or an iterable object but got [object Null]
ERR! Failed within
     at apiRejection (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/promise.js:10:27)
ERR! Failed within
     at MappingPromiseArray.init (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/promise_array.js:62:19)
ERR! Failed within
     at MappingPromiseArray._asyncInit (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/map.js:30:10)
ERR! Failed within
     at Async._drainQueue (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/async.js:143:12)
ERR! Failed within
     at Async._drainQueues (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/async.js:148:10)
ERR! Failed within
     at Immediate.Async.drainQueues [as _onImmediate] (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/async.js:17:14)
ERR! Failed within
     at tryOnImmediate (timers.js:543:15)
ERR! Failed within
     at processImmediate [as _immediateCallback] (timers.js:523:5)
ERR! Failed within
  TypeError: expecting an array or an iterable object but got [object Null]
ERR! Failed within
     at apiRejection (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/promise.js:10:27)
ERR! Failed within
     at MappingPromiseArray.init (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/promise_array.js:62:19)
ERR! Failed within
     at MappingPromiseArray._asyncInit (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/map.js:30:10)
ERR! Failed within
     at Async._drainQueue (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/async.js:143:12)
ERR! Failed within
     at Async._drainQueues (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/async.js:148:10)
ERR! Failed within
     at Immediate.Async.drainQueues [as _onImmediate] (/Users/spencerkohan/Projects/Professional/Telefonic/Code/contentful-import/node_modules/bluebird/js/release/async.js:17:14)
ERR! Failed within
     at tryOnImmediate (timers.js:543:15)
ERR! Failed within
     at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by Khaledgarbaya** [comment]
@spencerkohan Hi, Can you provide which version you used both for export and import

**Comment by spencerkohan** [comment]
thanks for getting back - the import version is 2.1.1.

I've already figured it out - my import JSON was missing the "assets" array.  I might suggest doing some validation of the import contents or adding defaults for missing properties - the error I got was not helpful for debugging since it gives no information about how or why it fails.
