### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by nursahketene** [contentful/contentful-import#66]
Getting error when trying to import data to another space (duplicate space for testing ui extensions) 

Stack

```
ERR! import TypeError: Cannot convert undefined or null to object
ERR! import     at Function.keys (<anonymous>)
ERR! import     at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)
ERR! import     at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)
ERR! import     at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)
ERR! import     at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)
ERR! import     at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)
ERR! import     at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)
ERR! import     at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)
ERR! import     at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)
ERR! import     at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)
ERR! import     at runCallback (timers.js:651:20)
ERR! import     at tryOnImmediate (timers.js:624:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:596:5)
ERR! import  { TypeError: Cannot convert undefined or null to object
ERR! import     at Function.keys (<anonymous>)
ERR! import     at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)
ERR! import     at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)
ERR! import     at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)
ERR! import     at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)
ERR! import     at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)
ERR! import     at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)
ERR! import     at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)
ERR! import     at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)
ERR! import     at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)
ERR! import     at runCallback (timers.js:651:20)
ERR! import     at tryOnImmediate (timers.js:624:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:596:5)
ERR! import   stack: 'TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)\n    at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)\n    at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)\n    at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)\n    at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)\n    at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)\n    at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:651:20)\n    at tryOnImmediate (timers.js:624:5)\n    at processImmediate [as _immediateCallback] (timers.js:596:5)' }
ERR! import TypeError: Cannot convert undefined or null to object
ERR! import     at Function.keys (<anonymous>)
ERR! import     at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)
ERR! import     at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)
ERR! import     at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)
ERR! import     at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)
ERR! import     at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)
ERR! import     at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)
ERR! import     at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)
ERR! import     at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)
ERR! import     at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)
ERR! import     at runCallback (timers.js:651:20)
ERR! import     at tryOnImmediate (timers.js:624:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:596:5)
ERR! import  Failed within
ERR! import  { TypeError: Cannot convert undefined or null to object
ERR! import     at Function.keys (<anonymous>)
ERR! import     at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)
ERR! import     at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)
ERR! import     at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)
ERR! import     at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)
ERR! import     at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)
ERR! import     at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)
ERR! import     at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)
ERR! import     at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)
ERR! import     at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)
ERR! import     at runCallback (timers.js:651:20)
ERR! import     at tryOnImmediate (timers.js:624:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:596:5)
ERR! import   stack: 'TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)\n    at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)\n    at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)\n    at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)\n    at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)\n    at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)\n    at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.
```

**Comment by Khaledgarbaya** [comment]
Hi @nursahketene ,

There is a rare that we still to investigate when asset.fields.file is null which is causing a crash.
I just released a fix for that in the contentful-management lib. It is a patch so if you install the contentful-import again you should get it (make sure to delete all the lock files or shrinkwrap)

Please update and try again, if you still have the problem please tell me.

Best,
Khaled

**Comment by nursahketene** [comment]
Thanks Khaled. I will give it a try tomorrow. and let you know about the progress.

**Comment by canvas-drw** [comment]
I am getting the same issue as above when trying to import. Any help would be much appreciated.

```
$ contentful-export --version
4.7.8
$ contentful-import --version
4.5.7
```

```
ERR! import TypeError: Cannot convert undefined or null to object
ERR! import     at Function.keys (<anonymous>)
ERR! import     at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)
ERR! import     at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)
ERR! import     at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)
ERR! import     at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)
ERR! import     at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)
ERR! import     at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)
ERR! import     at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)
ERR! import     at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)
ERR! import     at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)
ERR! import     at runCallback (timers.js:789:20)
ERR! import     at tryOnImmediate (timers.js:751:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:722:5)
ERR! import  { TypeError: Cannot convert undefined or null to object
ERR! import     at Function.keys (<anonymous>)
ERR! import     at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)
ERR! import     at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)
ERR! import     at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)
ERR! import     at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)
ERR! import     at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)
ERR! import     at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)
ERR! import     at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)
ERR! import     at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)
ERR! import     at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)
ERR! import     at runCallback (timers.js:789:20)
ERR! import     at tryOnImmediate (timers.js:751:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:722:5)
ERR! import   stack: 'TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)\n    at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)\n    at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)\n    at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)\n    at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)\n    at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)\n    at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)' }
ERR! import TypeError: Cannot convert undefined or null to object
ERR! import     at Function.keys (<anonymous>)
ERR! import     at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)
ERR! import     at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)
ERR! import     at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)
ERR! import     at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)
ERR! import     at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)
ERR! import     at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)
ERR! import     at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)
ERR! import     at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)
ERR! import     at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)
ERR! import     at runCallback (timers.js:789:20)
ERR! import     at tryOnImmediate (timers.js:751:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:722:5)
ERR! import  Failed within
ERR! import  { TypeError: Cannot convert undefined or null to object
ERR! import     at Function.keys (<anonymous>)
ERR! import     at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)
ERR! import     at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)
ERR! import     at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)
ERR! import     at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)
ERR! import     at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)
ERR! import     at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)
ERR! import     at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)
ERR! import     at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)
ERR! import     at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)
ERR! import     at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)
ERR! import     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)
ERR! import     at runCallback (timers.js:789:20)
ERR! import     at tryOnImmediate (timers.js:751:5)
ERR! import     at processImmediate [as _immediateCallback] (timers.js:722:5)
ERR! import   stack: 'TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at Object.processForAllLocales (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-management/dist/contentful-management.node.js:6995:26)\n    at _bluebird2.default.map.concurrency (/usr/local/lib/node_modules/contentful-import/node_modules/contentful-batch-libs/dist/push/assets.js:25:18)\n    at tryCatcher (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/util.js:16:23)\n    at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:61:38)\n    at MappingPromiseArray._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:115:14)\n    at MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/map.js:46:18)\n    at Promise._settlePromise (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:574:26)\n    at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:614:10)\n    at Promise._settlePromises (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/promise.js:693:18)\n    at Async._drainQueue (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:133:16)\n    at Async._drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-import/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:789:20)\n    at tryOnImmediate (timers.js:751:5)\n    at processImmediate [as _immediateCallback] (timers.js:722:5)' }
```

**Comment by axe312ger** [comment]
We are working on a fix, but this is not trivial to fix. I will keep u posted here :)

**Comment by sethreidnz** [comment]
No update on a fix?

**Comment by Khaledgarbaya** [comment]
Hi all,
It should be fixed in the next version `npm install -g contentful-import@next`.
Sorry for the late update.
Khaled

**Comment by sethreidnz** [comment]
I continue to struggle to get any sort of meaningful import. I now get a very obtuse error of `TypeError: Cannot read property 'processForAllLocales' of null`. Is there any other way to reliably move content from space to space? I need to move production data into a QA space for development and its impossible. Can I make it ignore assets?

**Comment by Khaledgarbaya** [comment]
Hey @sethreidnz are you sure you are using the `next` version ?

**Comment by sethreidnz** [comment]
`5.0.2-beta2`

**Comment by sethreidnz** [comment]
```

**Comment by sethreidnz** [comment]
Any ideas? I literally cannot import anything except some of the assets, and then it blows up. Is it possible to give us a new config value that is "skipAssets" so that we can import content and side step this entire problem while its being fixed? Do I need to also install the @next version of the export?

**Comment by Khaledgarbaya** [comment]
Hi @sethreidnz can you try now with `5.0.2-beta3`

**Comment by sethreidnz** [comment]
```

**Comment by sethreidnz** [comment]
For anyone who wants a work around, you just need to delete all assets that don't have an actual file saved to them and it will work.

**Comment by TorbenDalgaard** [comment]
> For anyone who wants a work around, you just need to delete all assets that don't have an actual file saved to them and it will work.

This is not a viable solution as this will happen any time a content editor add's an asset, publish it and then deletes the image.

Any help ? (using 5.0.2-beta4)

**Comment by sethreidnz** [comment]
Yeah its not really a "workaround" as much as a stop gap measure I used to get my data in once.
